CREATE TABLE IF NOT EXISTS user (
 id INTEGER PRIMARY KEY,
 email TEXT NOT NULL,
 first_name TEXT NOT NULL,
 last_name INTEGER NOT NULL,
 active INTEGER NOT NULL DEFAULT '0'
);


DROP TABLE IF EXISTS `post`;
CREATE TABLE IF NOT EXISTS post (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  author INTEGER NOT NULL
);
